################################# Default configuration ###################
# provide your domain here
baseURL = "https://examplesite.com/"
# theme
# theme = "dot"
# site title
title = "BCW知识库"
# DefaultContentLanguage
defaultContentLanguage = "zh-cn"
# disable language
disableLanguages = []
# google analytics
googleAnalytics = "" # paste your analytics ID here. (Ex: UA-123-45)

# unsafe html
[markup.goldmark.renderer]
unsafe= true

################################# navigation ################################
[[menu.main]]
name = "Faq"
url = "faq"
weight = 1

[[menu.main]]
name = "contact"
url = "contact"
weight = 2

# Dropdown menu
[[menu.main]]
weight = 3
name = "docs"
hasChildren = true

  [[menu.main]]
  parent = "docs"
  name = "Features"
  url = "features"
  weight = 3


############################# Default Parameters ##########################
[params]
# logo is for all page
logo = ""
# logo white is for homepage logo, you can use colorful logo too...
logo_white = ""
# when logo is empty, it will shown your site title

# customize color
primary_color = "#02007e"
body_color = "#f9f9f9"
text_color = "#636363"
text_color_dark = "#242738"
white_color = "#ffffff"
light_color = "#f8f9fa"

# font family
font_family = "Noto Serif SC" # Choose font family from : https://fonts.google.com/

# contact form action
contact_form_action = "#" # contact form works with : https://formspree.io


############################## social links ##############################

[[params.social]]
icon = "ti-github" # themify icon pack : https://themify.me/themify-icons
link = "#"


################################### Zh-cn Language ######################
[Languages.zh-cn]
languageName = "Zh-cn"
languageCode = "zh-cn"
weight = 1
home = "Home"
copyright = " copyright © [gethugothemes](https://gethugothemes.com/) 2020."

# banner
[Languages.zh-cn.params.banner]
title = "帮助中心和知识库"
subtitle = ""
bg_image = "images/banner.jpg"
placeholder = ""

# # call to action
[Languages.zh-cn.params.cta]
enable = true
title = "没有找到答案?"
content = ""
# call to action button
[Languages.zh-cn.params.cta.button]
enable = true
label = "联系我们"
link = "contact"

################################ English Language ######################
[Languages.en]
languageName = "En"
languageCode = "en-us"
weight = 2
home = "Home"
copyright = "The Hugo Documents are copyright © [gethugothemes](https://gethugothemes.com/) 2020."

# banner
[Languages.en.params.banner]
title = "帮助中心和知识库"
subtitle = ""
bg_image = "images/banner.jpg"
placeholder = ""

# call to action
[Languages.en.params.cta]
enable = true
title = "没有找到答案?"
content = ""
# call to action button
[Languages.en.params.cta.button]
enable = true
label = "contact us"
link = "contact"

